### ISSUE TITLE
unsigned executables

### ISSUE THREAD

**Issue by sanderdewit** [CSS-Windows/WindowsDiag#13]
Hello,

Thank you for this great toolkit!
We are using Microsoft Defender Application Control to control which files are allowed to be executed.
Hereby we have whitelisted the Microsoft standard certificates;
which can be found in %windir%\schemas\CodeIntegrity\ExamplePolicies\AllowMicrosoft.xml

The default Microsoft policy does not allow this toolkit to be run. When adding the certificates that are used to sign the files, this works, however the following files are not signed at all:
Can these files by signing to solve these issues? 

fruti_1903.exe
x86\myfault.x86\myfault.sys
x86\RecorderCommandLine.x86\RecorderCommandLine.exe
x86\RecorderDll.x86\RecorderDll.dll
x86\vsdiagview.x86\vsdiagview.exe
x64\RecorderCommandLine.x64\RecorderCommandLine.exe
x64\RecorderDll.x64\RecorderDll.dll
x64\vsdiagview.x64\vsdiagview.exe
fcinfo.fcinfo.exe
fruti_RS1.fruti_RS1.exe
hbatapi.hbatapi.dll
npivtool.npivtool.exe
poolmon.poolmon.exe
rpccfg.rpccfg.exe
rpcdump.rpcdump.exe
tss_DumpAdapterInfo.tss_DumpAdapterInfo.vbs
tss_EvtMon.tss_EvtMon.vbs
VmlTrace.VmlTrace.exe
VmlTrace_2012.VmlTrace_2012.exe
windowsperformancerecordercontrol.windowsperformancerecordercontrol.dll
wpr.wpr.exe
x86\cscdbdump.x86\cscdbdump.exe
x86\dfsutil.x86\dfsutil.exe
x86\get_dependencies.x86\get_dependencies.vbs
x86\NTttcp.x86\NTttcp.exe
x86\SdkDll.x86\SdkDll.dll
x86\vshadow.x86\vshadow.exe
x86\vssagent.x86\vssagent.exe
x86\vsstrace.x86\vsstrace.exe
x64\cscdbdump.x64\cscdbdump.exe
x64\dfsutil.x64\dfsutil.exe
x64\latte.x64\latte.exe
x64\NTttcp.x64\NTttcp.exe
x64\SdkDll.x64\SdkDll.dll
x64\takeshot.x64\takeshot.exe
x64\vshadow.x64\vshadow.exe
x64\vssagent.x64\vssagent.exe
x64\vsstrace.x64\vsstrace.exe
WIP\RingQuery\Checkwin32enlightened.WIP\RingQuery\Checkwin32enlightened.exe
WIP\RingQuery\querytokenX64.WIP\RingQuery\querytokenX64.exe
WIP\RingQuery\querytokenX86.WIP\RingQuery\querytokenX86.exe
WIP\LogPackages\EDP\dpmcmd_amd64.WIP\LogPackages\EDP\dpmcmd_amd64.exe
WIP\LogPackages\EDP\dpmcmd_ARM64.WIP\LogPackages\EDP\dpmcmd_ARM64.exe
WIP\LogPackages\EDP\dpmcmd_x86.WIP\LogPackages\EDP\dpmcmd_x86.exe

**Comment by walter-1** [comment]
Thx sanderdewit, for your hint. Status: we are currently in the phase of getting those MS support executables digitally signed.
(a few of the reported executables, which are not necessary for data **collection**, are removed already in latest package)
