### ISSUE TITLE
Virus Detection on Release

### ISSUE THREAD

**Issue by infraweavers** [CSS-Windows/WindowsDiag#8]
Hi,

Release https://github.com/CSS-Windows/WindowsDiag/releases/tag/2020.09.30.1 shows as a virus in Vipre Endpoint Protection

![popup](https://user-images.githubusercontent.com/36475663/94908546-bd74fc00-0499-11eb-8dd4-af42d269500d.png)

![VipreEndpointSecurity](https://user-images.githubusercontent.com/36475663/94908412-869ee600-0499-11eb-8732-258abc44d0bb.png)

It doesn't show as a virus on here: https://www.virustotal.com/gui/file/3a0e771a5773b65a5f68ca131a00f1a3d1f4d114b645d9e2909f568d89b64e57/detection

[Virus.txt](https://github.com/CSS-Windows/WindowsDiag/files/5317061/Virus.txt)

**Comment by walter-1** [comment]
MS Defender team is the source/developer of this script. It's a false positive.

**Comment by walter-1** [comment]
sorry for delayed answer, thx anyways for your hint, infraweavers!
